### ISSUE TITLE
Upgrade unicorn plugin to v24

### ISSUE THREAD

**Issue by tclindner** [tclindner/eslint-config-tc#268]
https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v24.0.0

- [x] Add new rules. 
- [x] Update `peerDeps` on current version before releasing a new major version. https://github.com/tclindner/eslint-config-tc/releases/tag/v16.4.0

**Comment by pohnemus** [comment]
Sindre seems to add the new rules to the `recommended` ruleset on each release fyi.
