### ISSUE TITLE
Consider adding jest/prefer-spy-on

### ISSUE THREAD

**Issue by tclindner** [tclindner/eslint-config-tc#86]
https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/prefer-spy-on.md

**Comment by keisha-rw** [comment]
I'm on the fence on this one.  I can see where it'd be nice, but since we're restoring mocks I don't think this has been an issue in the past.  It would require a lot of rewrite but I don't think it'd benefit us all that much.

**Comment by phil-rw** [comment]
I don't even know what this means :)

**Comment by tclindner** [comment]
Thanks for the input! Closing
